steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-west1-docker.pkg.dev/nest-microservices-430412/image-registry/orders-ms-prod',
        '-f',
        'Dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-west1-docker.pkg.dev/nest-microservices-430412/image-registry/orders-ms-prod',
      ]
options:
  logging: CLOUD_LOGGING_ONLY
